### ISSUE TITLE
DM improvements

### ISSUE THREAD

**Issue by will-hanlen** [urbit/shrub#14]
negotiator shrub which sets up mutual DM subscriptions and hub-and-spoke groupchats.

future milestone: users can accept or reject DM and groupchat joins.

stretch goal: pull in Circles to populate options for who to start DMs/groupchats with

**Comment by hanfel-dovned** [comment]
From #11:

_"but we probably want to move to a different architecture:

aggregator
publisher
subscriber."_

**Comment by hanfel-dovned** [comment]
- also need to fix the ~zod bowl issue

**Comment by hanfel-dovned** [comment]
I've split the logic between a publisher and a subscriber shrub. This feels cleaner on the backend side, but there's a lot of code re-use on the rendering side.

Next steps are to fix a synching bug with the subscriber dependencies and add UI elements for creating a new DM and adding people to a DM. 

(Does "DM" imply only two people? These are multi-party now.)

**Comment by will-hanlen** [comment]
our.bowl issue is fixed, but still need to rework all the con files to use an updated here.bowl which also includes the our

**Comment by tiller-tolbus** [comment]
* top-level shrub is called `chat`
* `chat` maintains intermediate state while negotiating the existence of DMs and groupchats
  * for example, if `~zod` invites `~nec` to a group chat and `~nec` needs to accept, `chat` is responsible for knowing whether or not ~nec has accepted the invite
* user can create a DM or a groupchat
* DMs are uniquely categorized and named by `@p`, groups are given custom names
* DM subscriptions are mutual
  * ex. `~nec/chat/~zod/theirs` <> `~zod/chat/~nec/ours`, `~zod/chat/~nec/theirs` <> `~nec/chat/~zod/ours`
  * groups hub-and-spoke using Liam's `%chat` and `%chat-link` examples, but renamed so that the negotiator can be called `chat`

**Comment by tiller-tolbus** [comment]
DM and groupchat UIs should have iMessage-style chat bubbles (on the right-hand side if it's your message and left-hand side if it's somebody else's)

**Comment by hanfel-dovned** [comment]
**lib/messages.hoon**
- [x] put `.loader` in correct spot
- [ ] iMessage-style chat bubbles

**con/messenger.hoon**
- [x] display all dms and groupchats. clicking on one takes you to its UI
- [x] for groupchats, have a dropdown:
  - [x] that lists participants
  - [x] if I'm the host, have an X next to name to remove participant
  - [x] if I'm the host, have a box that lets me add a new participant

**Testing**
- [ ] test extensively on multiple ships
