### ISSUE TITLE
Short-term deliverables for dev summit

### ISSUE THREAD

**Issue by tiller-tolbus** [urbit/shrub#63]
**Accel**
- [ ] user can add a dependency to sky settings from a foreign ship and poke said settings into their own sky settings, refresh the page and see the settings applied
- [ ] adding a dependency that does not resolve doesn't introduce any show-stopping behavior

**Docs**
- [x] add everything that is not "introduction" and "feather" to a folder called "tutorials" within imp/home init sequence; remove "chapter 0" from introduction title
- [x] add to dev setup common troubleshooting steps, such as `|nuke %neo` and `|start %neo`, take note of other common troubleshooting patterns that occur during today's workshop and include those as well. 
- [x] comb through docs, remove any language that is self-deprecating and replace it with descriptions of problematic phenomena
- [x] remove the .md docs files from /fil. the .txt ones are the up-to-date ones
- [ ] _stretch goal: show how to inspect state of counter with debug output sample_
- [ ] _stretch goal: Sky usage guide by migrev_
- [ ] _stretch goal: sur/neo types, working with piths, pishes, ports, welding and snoccing piths_

**Messenger**
- [x] automatic refreshing of received messages
- [x] scrolling through long chat histories
- [x] clean up timestamps
- [x] auto-scrolling within long chat histories
- [x] starting a chat with existing counterparty doesn't overwrite anything 

**Sky**
- [ ] create new sky pill at end of workshop, include link to sky pill in environment setup doc
- [ ] _stretch goal: merge in c1-demos branch, create new pill with this included_

**Comment by hanfel-dovned** [comment]
- [ ] Need a warning about infinite loops somewhere

**Comment by hanfel-dovned** [comment]
We should really get the terminal output quieted down before release.

**Comment by tiller-tolbus** [comment]
> We should really get the terminal output quieted down before release.

This is allegedly just a single flag that can be flipped during the desk shrub release

**Comment by hanfel-dovned** [comment]
Current status on the incompleted sub-issues here:

- When we try to add a remote dependency in accel, we get some gargantuan error output, similar to the errors we were getting in Messenger yesterday prior to hastuc's fix, but continuous and longer. @liam-fitzgerald some help with this and the point below would be great.
- Related, there seems to be a lot of extraneous error output related to dependencies in general; our hypothesis is that `%tomb`-ing a `hawk-eyre-handler` doesn't tell its dependencies to stop poking it with relies, leading to compoundingly long load times the longer you use Sky.
- Adding items to a folder within a folder in this specific way would require changing `imp/folder` a bit, didn't seem like the best use of time today.
- It probably makes more sense to wait to make a new Sky pill until after everything is ready for launch, otherwise we'll have to re-do it anyway.

**Comment by hanfel-dovned** [comment]
We also need to make sure to flag the possibility of infinite loops before releasing this to people's real ships.

**Comment by tiller-tolbus** [comment]
Dev summit has passed, if we are going to do any of these they are going to be new issues
